### PR TITLE
solana: fix lamport beneficiaries

### LINKED ISSUE #104: solana: Add a way to refund the payer of the custody_token when an offer is placed
The initial offer token is refunded its USDC but the lamports are not correctly refunded for the payer who created the custody_token account.

### PR DESCRIPTION
**Pull request by a5-pickle**
* Execute order should send auction custody token account lamports to the owner of the initial offer token if it exists
* Settle auction none should send prepared custody token lamports to prepared_by encoded in `PreparedOrderResponse`
* Place order CCTP should send prepared order token account lamports to prepared_by encoded in `PreparedOrder`

Closes #104.

### CODE REVIEW

**Review by johnsaigle — COMMENTED** [review]
I think the account close changes look good. 

I'm curious the values are being extracted from ExecuteOrder now instead of passing the struct along directly as before?

**Comment by a5-pickle** [comment]
> I think the account close changes look good.
> 
> I'm curious the values are being extracted from ExecuteOrder now instead of passing the struct along directly as before?

Do you mean here? https://github.com/wormhole-foundation/example-liquidity-layer/blob/769790ca7c96eb997c6376fc1c0ac10e773afb27/solana/programs/matching-engine/src/processor/auction/execute_fast_order/mod.rs#L21-L27.

I did this because I lazily passed a mutable reference to the whole ExecuteOrder composite before. I think passing each account from this context reflecting whether each account should be a static ref or mut ref feels better. What do you think?

**Comment by a5-pickle** [comment]
> As I look at this more, it's an interesting trade off of whether to pass specific references of each account from the composite. Or to pass the composite to leave it less error-prone to reference each account in the composite.
> 
> I guess inside the shared method I could specify static references to specific accounts. Is that preferred?

Made the change here: https://github.com/wormhole-foundation/example-liquidity-layer/pull/109/commits/731df932494c54f879d53d819de429072775afa2. This does feel better. What do you think?

File: solana/programs/matching-engine/src/processor/auction/execute_fast_order/mod.rs [hunk 1]
```diff
@@ -23,38 +23,36 @@ struct PrepareFastExecution<'ctx, 'info> {
...
-        initial_offer_token,
-    } = execute_order;
-
-    let ActiveAuction {
-        auction,
-        custody_token,
-        config,
-        best_offer_token,
-    } = active_auction;
+    let auction = &mut execute_order.active_auction.auction;
```
Comment (gator-boi) [inline solana/programs/matching-engine/src/processor/auction/execute_fast_order/mod.rs:41]: Look at all those references.

**Review by gator-boi — APPROVED** [review]

**Comment by a5-pickle** [comment]
Going to merge this. @johnsaigle if you have a strong opinion about how the refs should be passed, I'll put up another PR after we discuss it.

File: solana/programs/matching-engine/src/processor/auction/execute_fast_order/mod.rs (hunk 1 above)
Comment (a5-pickle) [reply solana/programs/matching-engine/src/processor/auction/execute_fast_order/mod.rs:41]: :chicken:
