### PR TITLE
LL: Fix encoded redeemer message length

### LINKED ISSUE #105: solana: Limit redeemer message size
We should think about how large these redeemer messages will be though, even though it would be unlikely they reach lengths greater than the max size of a Solana account.

_Originally posted by @a5-pickle in https://github.com/wormhole-foundation/example-liquidity-layer/pull/103#discussion_r1581251514_

The current limit of a redeemer message is u32::MAX on the level of the code (message serialization) though significantly shorter due to Solana runtime constraints (account size, CU cost,...)

This is fine but it would be better to bound this to something realistic and make it more explicit what these messages should look like.

### PR DESCRIPTION
**Pull request by gator-boi**
The purpose of this PR is to restrict the redeemer message size to u16 in both EVM and Solana. This PR also introduces a max redeemer message length of 500 bytes to ensure that all LL messages can safely be posted on Solana. 

Closes #105

### CODE REVIEW

File: solana/programs/matching-engine/src/processor/auction/prepare_order_response/cctp.rs [hunk 1]
```diff
@@ -74,8 +74,8 @@ pub struct PrepareOrderResponseCctp<'info> {
                 .fast_market_order()
                 .ok_or(MatchingEngineError::InvalidPayloadId)?;
 
-            // This is safe to unwrap because the length will not exceed u32.
-            order.redeemer_message_len().try_into().unwrap()
+            // This is safe to unwrap because the length will not exceed u16.
```
Comment (a5-pickle) [inline solana/programs/matching-engine/src/processor/auction/prepare_order_response/cctp.rs:77]: Can remove this comment since the safety is implied by `Into`

File: solana/programs/token-router/src/processor/redeem_fill/cctp.rs [hunk 2]
```diff
@@ -294,7 +294,7 @@ fn try_compute_prepared_fill_size(fill_vaa: &LiquidityLayerVaa) -> Result<usize>
         .fill()
         .ok_or(TokenRouterError::InvalidDepositPayloadId)?;
 
-    // It is safe to unwrap the redeemer message length because u32 -> usize is infallible.
-    PreparedFill::checked_compute_size(fill.redeemer_message_len().try_into().unwrap())
+    // It is safe to unwrap the redeemer message length because u16 -> usize is infallible.
+    PreparedFill::checked_compute_size(fill.redeemer_message_len().into())
         .ok_or(error!(TokenRouterError::PreparedFillTooLarge))
```
Comment (a5-pickle) [inline solana/programs/token-router/src/processor/redeem_fill/cctp.rs:299]: We can call `unwrap` instead of `ok_or` here due to the redeemer message constraint. Either that or remove the infallible comment (I think I accidentally left that in with my last PR).

File: solana/programs/token-router/src/processor/redeem_fill/cctp.rs [hunk 3]
```diff
@@ -294,7 +294,7 @@ fn try_compute_prepared_fill_size(fill_vaa: &LiquidityLayerVaa) -> Result<usize>
         .fill()
         .ok_or(TokenRouterError::InvalidDepositPayloadId)?;
 
-    // It is safe to unwrap the redeemer message length because u32 -> usize is infallible.
-    PreparedFill::checked_compute_size(fill.redeemer_message_len().try_into().unwrap())
+    // It is safe to unwrap the redeemer message length because u16 -> usize is infallible.
```
Comment (a5-pickle) [inline solana/programs/token-router/src/processor/redeem_fill/cctp.rs:297]: We can remove this comment, too.

**Review by johnsaigle — APPROVED** [review]
Looks good - constant values seem to be changed consistently. Both Solidity and Solana sides should fail when messages exceed 500 bytes.

**Review by a5-pickle — APPROVED** [review]
