### PR TITLE
solana: fix local custody owner

### LINKED ISSUE #34: solana: change local custody token authorities to each source chain's router endpoint
Currently the authority for all local custody accounts is the local router endpoint.

Maybe we should make these authorities each be their respective chain's router endpoints?

### PR DESCRIPTION
**Pull request by a5-pickle**
Closes #34.

### CODE REVIEW

File: solana/programs/token-router/src/processor/redeem_fill/cctp.rs [hunk 1]
```diff
@@ -1,142 +1,96 @@
...
+}
+
+/// Accounts required for [redeem_cctp_fill].
+#[derive(Accounts)]
+pub struct RedeemCctpFill<'info> {
+    custodian: CheckedCustodian<'info>,
+
+    prepared_fill: InitIfNeededPreparedFill<'info>,
+
+    /// Registered emitter account representing a Circle Integration on another network.
```
Comment (gator-boi) [inline solana/programs/token-router/src/processor/redeem_fill/cctp.rs:76]: Stale comment?

**Review by gator-boi — APPROVED** [review]
